// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test', async function() {
    await driver.get("http://127.0.0.1:5500/Month-1/Week-1/day-01/js/index.html")
    await driver.manage().window().setRect(1294, 1040)
    await driver.findElement(By.id("input")).click()
    await driver.findElement(By.id("input")).sendKeys("em minusculo")
    await driver.findElement(By.id("button")).click()
    assert(await driver.switchTo().alert().getText() == "Alguma letra esta minuscula")
    await driver.findElement(By.id("input")).click()
    await driver.findElement(By.id("input")).sendKeys("Nem Todas Em Minusculo")
    await driver.findElement(By.id("button")).click()
    assert(await driver.switchTo().alert().getText() == "Alguma letra esta minuscula")
    await driver.findElement(By.id("input")).click()
    await driver.findElement(By.id("input")).sendKeys("TODAS EM MAIUSCULO")
    await driver.findElement(By.id("button")).click()
    assert(await driver.switchTo().alert().getText() == "Esta tudo maiúsculo")
  })
})
